AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

#Style/StringLiterals:
#  Enabled: true
#  EnforcedStyle: double_quotes
#
#Style/StringLiteralsInInterpolation:
#  Enabled: true
#  EnforcedStyle: double_quotes

#Layout/LineLength:
#  Max: 120
