AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
