AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/GlobalStdStream:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
